version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "21:00"
    open-pull-requests-limit: 10
    # Overwrite any ignores created using `@dependabot ignore` commands
    ignore:
      # Ignore updates to packages that start 'aws'
      # Wildcards match zero or more arbitrary characters
      #- dependency-name: "aws*"
      # Ignore some updates to the 'resteasy' package
      - dependency-name: "jakarta.platform:jakarta.jakartaee-api"
        # Ignore only new versions for 4.x
        versions: [ "9.x" ]
        update-types: minor
      - dependency-name: "org.glassfish.jaxb:jaxb-runtime"
        versions: [ "3.x" ]
        update-types: minor
          
