package org.eclipse.cargotracker.domain.model.cargo;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;
import jakarta.validation.constraints.NotEmpty;

import java.io.Serializable;

/** Uniquely identifies a particular cargo. Automatically generated by the application. */
@Embeddable
//@formatter:off
public record TrackingId(

	@NotEmpty(message = "Tracking ID cannot be empty.")
	@Column(name = "tracking_id", unique = true, updatable = false)
	String id
) implements Serializable {
//@formatter:on

	boolean sameValueAs(TrackingId other) {
		return other != null && this.id.equals(other.id);
	}
}