version: 2.1

orbs:
  maven: circleci/maven@1.2.0
executors:
  docker-build:
    docker:
      - image: circleci/openjdk:11-jdk
      - image: circleci/postgres:latest
        command:
          - "--max_prepared_transactions=110"
        #auth:
        #  username: user
        #  password: password
        environment:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: cargotracker
jobs:
  build:
    executor: docker-build
    steps:
      - checkout
      - maven/with_cache:
          steps:
            - run:
                name: Analyze on SonarCloud
                command: |
                  mvn clean verify -Parq-payara-managed,coverage jacoco:report \
                  org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
                  -Dsonar.host.url=https://sonarcloud.io \
                  -Dsonar.login=$SONAR_TOKEN \
                  -Dsonar.organization=hantsy \
                  -Dsonar.projectKey=hantsy_cargotracker \
                  -Dsonar.coverage.exclusions=**/dto/*
      - maven/process_test_results
workflows:
  main:
    jobs:
      - build
#          context: SonarCloud
#          filters:
#            branches:
#              only: master
