name: arq-wildfly-managed

on:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      MAVEN_OPTS: >-
        -Dorg.slf4j.simpleLogger.defaultLogLevel=debug
        -Dorg.slf4j.simpleLogger.log.org.hibernate=debug
        -Dorg.jboss.logging.provider=slf4j
        -Dhibernate.show_sql=true
        -Dhibernate.format_sql=true

    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: "zulu"
          java-version: "21"
          cache: "maven"
      - name: Set up Database
        run: |
          docker compose down -v || true
          docker volume prune -f || true
          docker compose up -d postgres
          sleep 10
          docker ps -a
      - name: Build with Maven
        run: mvn -X clean verify -Parq-wildfly-managed
