name: build

on:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - if: github.event_name != 'pull_request'
        uses: actions/checkout@v3
      - if: github.event_name == 'pull_request'
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      # Recommended: latest versions of Google Java Format require JDK 11+
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "11"
      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--aosp  --skip-reflowing-long-strings --skip-sorting-imports --replace"
          #  version: 1.9
          # Recommended if you use MacOS:
          # githubToken: ${{ secrets.GITHUB_TOKEN }}
          # set dry-run and will not commit by default
          # skipCommit: false
  build:
    runs-on: ubuntu-latest
    needs: [ formatting ]
    strategy:
      matrix:
        distribution: ['temurin', 'zulu']
        # test against latest update of each major Java version, as well as specific updates of LTS versions:
        java: [ 11, 17 ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: ${{matrix.distribution}}
          java-version: ${{matrix.java}}
          cache: 'maven'
      - name: Build with Maven
        run: mvn clean package --file pom.xml
