name: it-with-arq-wildfly-managed

on:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  it-with-arq-wildfly-managed:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'maven'

      - name: Start up databases via Docker Compose
        run: |
          docker-compose up -d postgres
          docker ps -a
      - name: Cache SonarCloud packages
        uses: actions/cache@v3.2.6
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run integration test with -Parq-wildfly-managed
        run: mvn clean verify -Parq-wildfly-managed,wildfly
