name: it-with-arq-payara-micro

on:
  push:
    paths-ignore:
      - "docs/**"
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  it-with-arq-payara-micro:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Start up databases via Docker Compose
        run: |
          docker-compose up -d postgres
          docker ps -a

      - name: Cache Maven packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run integration test with -Parq-payara-micro
        run: mvn clean verify -Parq-payara-micro
